version:  '3'

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/wordpress
    restart: on-failure
    env_file: .env


  mariadb:
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: on-failure
    env_file: .env
  
  wordpress:
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/wordpress
    expose:
      - "9000"
    env_file: .env

volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/sbeylot/data/wordpress

  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/sbeylot/data/mariadb

networks:
  inception:
    driver: bridge



    